services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    restart: unless-stopped

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/:/data
    restart: unless-stopped
