services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    restart: unless-stopped

  bot:
    build:
      context: ./aurene-bot
    depends_on:
      - redis
    env_file:
      - ./aurene-bot/.env
    command: npm run start
    restart: unless-stopped

  dashboard:
    build:
      context: ./aurene-dashboard
    depends_on:
      - redis
    env_file:
      - ./aurene-dashboard/.env
    ports:
      - "3000:3000"
    command: npm run start
    restart: unless-stopped
